config/routes.rb
Rails.application.routes.draw do

  # Routes for Pcloud portal
  constraints :host => Settings.environments.portal_domain do
    devise_scope :user do
      # setting root path to welcome index page, if user signed in
      authenticated :user do
        root 'welcome#index', as: :authenticated_root
      end

      # setting root path to sign in page, if user not sign in
      unauthenticated do
        root 'sessions#new', as: :unauthenticated_root
      end
    end

    use_doorkeeper scope: 'oauth' do
      controllers authorizations: 'oauth2/authorizations',
                  tokens: 'oauth2/tokens',
                  applications: 'oauth2/applications',
                  authorized_applications: 'oauth2/authorized_applications'
    end
    get 'oauth/logout', to: 'oauth2/authorizations#logout'

    get 'hint/signup'
    get 'hint/confirm'
    get 'hint/reset'
    get 'hint/sent'
    get 'hint/agreement'
    get 'hint/confirm_sent'
    get 'help', to: 'help#index'

    devise_for :users, :controllers => {
      :registrations => "registrations",
      :confirmations => 'confirmations',
      :sessions => "sessions",
      :passwords => 'passwords',
      :omniauth_callbacks => "users/omniauth_callbacks"}

    devise_scope :user do
      get   'users/confirmation/edit', to: 'confirmations#edit'
      patch 'users/confirmation',      to: 'confirmations#update'
      get   'oauth/new',               to: 'users/omniauth_callbacks#new'
      post  'oauth/new',               to: 'users/omniauth_callbacks#confirm'
      get   'oauth/login',             to: 'users/omniauth_callbacks#login'
      post  'oauth/login',             to: 'users/omniauth_callbacks#logining'
    end

    get 'personal/profile'

    scope module: 'oauth2' do
      namespace :api do
        namespace :v1 do
          get 'my/info', to: 'my#info', format: 'json'
        end
      end
    end

    scope :path => '/d/oauth', :module => "api/devices" do
      post 'authorize', to: 'authorize#create', format: 'json'
    end

    scope :path => '/healthy/1/', :module => "api/healthy" do
      get 'status', to: 'status#show', format: 'json'
    end
  end

  # Catch all routes
  root "application#raise_not_found!", via: :all
  get "*path", to: "application#raise_not_found!", via: :all
end

app/controllers/hint_controller.rb
class HintController < ApplicationController

  skip_before_action :check_user_confirmation_expire
  before_action :get_info

  def confirm
  end

  def signup
    if session[:notice]
      @success_info = session[:notice].split(".").first + "."
    end
  end

  def sent
  end

  def reset
  end

  def agrement
  end

  def confirm_sent
  end

  private
    def get_info
      if flash[:notice]
        session[:notice] = flash[:notice]
      end
    end
end

app/views/hint/_agreement.html.erb
歡迎您選擇加入成為合勤科技ZyXEL會員，請您先詳讀以下使用條款。 這些使用條款訂立的目的，是為了保護會員服務的提供者以及所有使用者的利益，並構成使用者與會員服務提供者之間的契約，使用者完成註冊手續、或開始使用合勤科技ZyXEL會員服務時，即視為已知悉、並完全同意本使用條款的所有約定：
<br>
<br>
■會員保管密碼的義務<br> 
1. 會員應該妥善保管密碼，不可以將密碼洩露或提供給其他人知道或使用；以同一個會員帳號和密碼所進行的所有行為，都將被認為是該會員本人和密碼持有人的行為。<br>
2. 會員註冊時必須填寫確實之個人資料，若發現有不實登錄時，合勤科技ZyXEL得以暫停或終止其會員資格，若違反中華民國或會員所在地相關法律，亦將依法追究。<br>
3. 會員如果發現或懷疑有第三人使用其會員帳號或密碼，應該立即通知合勤科技ZyXEL，採取必要的防範措施。
<br>
■會員的隱私權保障<br>
1. 在下列的情況下，合勤科技ZyXEL有可能會查看或提供會員個人或相關電信資料給有權機關、或主張其權利受侵害並提出適當證明之第三人：<br>
一、基於法律之規定。<br>
二、受司法機關或其他有權機關基於法定程序之要求。<br>
三、在緊急情況下為維護其他會員或第三人之人身安全。<br>
四、會員透過合勤科技ZyXEL活動而產生的金流、物流必要資訊。<br>
2.對於會員所登錄或留存之個人資料，在未獲得會員同意以前，合勤科技ZyXEL絕不對外揭露會員之姓名、地址、電子郵件地址及其他依法受保護之個人資料。<br>
3.同時為提供行銷、市場分析、統計或研究、或為提供會員個人化服務或加值服務之目的，會員同意合勤科技ZyXEL、或策略合作夥伴，得記錄、保存、並利用會員在本網站所留存或產生之資料及記錄，同時在不揭露各該資料之情形下得公開或使用統計資料。<br>
4.會員同意由合勤科技ZyXEL提供不定期寄送各類活動訊息及其他內容資訊。<br>
■ 禁止使用事項。<br>
1. 僅可用於合法用途。 會員僅可以將合勤科技ZyXEL的服務及會員的裝置用於合法、正當及適當的用途。會員不得以不合法、不正當或不適當的方式使用合勤科技ZyXEL的服務及會員的裝置。  <br>
2. 監控。 合勤科技ZyXEL會監控是否有任何使用合勤科技ZyXEL的服務從事違反本協議的活動。如果合勤科技ZyXEL懷疑有違反本協議的活動，或如果合勤科技ZyXEL認為需要保護合勤科技ZyXEL的服務或其母公司、關係企業、董事、主管、代理商及員工免於傷害，我們將會中斷或攔截所有通訊。   <br>
3. 提供資訊給官方機構和第三方。 如果合勤科技ZyXEL認定會員已將合勤科技ZyXEL的服務及會員的裝置用於非法用途，合勤科技ZyXEL會將相關的通聯記錄及其他資訊 (包括會員的身分識別) 轉交予適當的檢調單位以便其進行調查。會員同意合勤科技ZyXEL將任何此類通聯記錄與資訊轉交給這些機構。此外，合勤科技ZyXEL可以依照以下的要求，揭露會員的姓名、電話號碼、信用卡資訊以及其他的個人資訊、任何會員所發出和收到的通聯往來資料，以及任何其他合勤科技ZyXEL所擁有關於會員帳戶的資訊，包括但不限於服務的類型、服務年資、MAC 位址、IP 位址、電子郵件地址及所有其他帳戶資訊： <br>
1. 為了回覆執法或其他政府機構的要求； <br>
2. 依照法律、法規、條例、傳票、搜索票或法院命令的要求； <br>
3. 為了識別、連絡，或針對可能不當使用服務及/或裝置的人採取法律行動所需； <br>
4. 用以保障合勤科技ZyXEL 的權益及資產；或 <br>
5. 在有需要揭露此類資訊以保護 合勤科技ZyXEL的客戶或第三方免於急迫傷害的緊急狀況下。
<br>
■ 免責聲明。<br>
合勤科技ZyXEL網站上的資訊，以及合勤科技ZyXEL 服務和產品，均以「原狀」提供。合勤科技ZyXEL不提供任何其他明示或默示之擔保，包括但不限於商業適售性、特定用途之服務或產品的適用性、所有權或不侵害他人權益的任何默示擔保，或任何因為交易使用、處理過程或履約過程所產生之擔保。此外，我們不保證合勤科技ZyXEL 網站、服務或產品不會故障、延遲、中斷、錯誤、聲音品質不良，亦不保證不會遺失內容、資料或資訊。   會員謹此承認某些合勤科技ZyXEL產品和服務並未加密，而該等資訊在與合勤科技ZyXEL、服務或產品往返傳輸過程中可能遭到攔截，且合勤科技ZyXEL不保證使用本軟體、合勤科技ZyXEL網站、服務或產品是絕對安全的。會員謹此同意承擔在傳輸此類資訊過程中，與會員資訊遭到未授權存取相關聯的任何及一切風險。   對未經授權使用合勤科技ZyXEL的或會員的傳輸設施或周邊設備，或未經授權存取以透過意外、詐騙手段、裝置或任何其他方式改動、盜竊或破壞會員的資料檔案、程式、程序或資訊，不論此損害是否導因於合勤科技ZyXEL或其服務提供者或廠商的疏失，無論合勤科技ZyXEL或其主管、董事、員工、關係企業、供應商或代理商，或是任何其他服務提供者或就我們的服務提供服務、裝置或產品給客戶的廠商，都不會對此類損害承擔任何賠償責任。   合勤科技ZyXEL或合勤科技ZyXEL的代理商或供應商對我們的服務或裝置所發表的聲明和敘述僅為通知性質，不可作為任何形式的擔保。由於此網站提供國際性的資訊，因此並非所有提及的產品、價格或程式都會在會員所在的國家/地區提供。請洽會員當地的業務代表以瞭解在貴國可用的產品與服務。   雖然合勤科技ZyXEL試圖在合勤科技ZyXEL網站上提供正確的資訊，但合勤科技ZyXEL對於資訊的準確性不承擔任何責任。合勤科技ZyXEL得隨時變更本協議中提及的程式或產品，恕不另行通知。本協議中提及的非合勤科技ZyXEL產品或服務僅供作參考資訊，並非為使用該等產品或服務背書或建議。 
<br>
■ 責任的限制。<br>
在任何情況下，合勤科技ZyXEL、其主管、董事、關係企業、員工、授權者或網路服務提供者，對於包括任何直接、間接、意外、附加、因果性或懲戒性的損害、訴訟或花費在內的任何損害均不承擔任何責任，諸如但不限於商譽、利潤或資料或營運中斷的損失，起因於或相關於本協議及/或本協議所預期的交易，包括使用或無法使用合勤科技ZyXEL網站、服務及/或產品、無法透過緊急撥號服務找到緊急維修人員或取得緊急援助，以及未經授權存取或變更會員的通聯或資料，即便合勤科技ZyXEL已獲知上述損害之可能性時亦同。由於入侵和攻擊網路及擷取傳入和傳出資料的新技術不斷被開發出來，因此 合勤科技ZyXEL不保證使用產品、軟體或服務的產品、軟體或服務或是任何設備、系統或網路，完全沒有可被利用於入侵、攻擊或擷取資料的漏洞。   由於某些司法管轄地區不允許排除或限制默示擔保或衍生性或附隨損害賠償之責任，因此訂定於本條款中的限制可能不適用於會員。 隨所在司法管轄地區不同，會員可能還擁有其他法律權利。 這些限制適用於法律所允許的最大限度。 
<br>
■智慧財產權<br>
合勤科技ZyXEL網站上之所有著作及資料，其著作權、專利權、商標、營業秘密、其他智慧財產權、所有權或其他權利，均為合勤科技ZyXEL或其原始著作人所有，除事先經合勤科技ZyXEL或其權利人之合法授權外，會員不得擅自重製、傳輸、改作、編輯或以其他任何形式、基於任何目的加以使用，否則應負法律責任。
<br>
■ 放棄索賠或起訴理由。<br>
會員放棄所有起因於或相關於我們的服務的索賠或訴訟理由，除非此索賠或起訴理由起因於我們的嚴重疏忽、冒失或有意的失誤。 
<br>
■ 協議變更。<br>
我們可能隨時藉由在 合勤科技ZyXEL網站上發佈經過修訂的條款來修訂本協議。 會員繼續使用合勤科技ZyXEL網站、服務及/或產品，將構成會員接受此項經過修正的協議。 除非是以書面形式由會員與我們共同簽署，否則本協議不得以任何其他方式修訂。
<br>
■個別條款之效力<br>
本約定之任何條款之全部或一部份無效時，不影響其他約定之效力。
<br>
■準據法及管轄法院<br>
合勤科技ZyXEL對於會員與本公司的權利義務關係，應依應依網路規範及中華民國法律定之；若產生任何爭議以第一審管轄法院為台北地方法院。
合勤科技ZyXEL的任何聲明、條款如有未盡完善之處，將以最大誠意，依誠實信用、平等互惠原則，共商解決之道。
<br>
■會員身份終止<br>
合勤科技ZyXEL具有更改各項服務內容或終止任一會員帳戶服務之權利，同時將以電子郵件通知會員。
<br>
■網站災害<br>
會員申請加入屬免費性質，會員瞭解並同意，合勤科技ZyXEL系統運作可能會因有關電信業者網路系統軟硬體設備之故障或失靈或因天災等不可抗力因素而出現中斷、故障、延遲、資料傳輸或儲存錯誤，合勤科技ZyXEL對於因此所生之損害，不負賠償或補償之責任。

app/views/hint/_sign_on_agreement_terms.html.erb
<div class="modal fade" id="user_agreement_dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button> -->
        <h4 class="modal-title" id="myModalLabel"><%= I18n.t("titles.terms") %></h4>
      </div>
      <div class="modal-body" style="overflow-y: scroll; height: 300px; color: #000">
        <% if I18n.locale.to_s  == "zh-TW" %>
          <%= render "/hint/terms/zh_TW" %>
        <% else %>
          <%= render "/hint/terms/en" %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>

app/views/hint/_terms.html.erb
Welcome to become a member of ZyXEL. Please first read carefully the following Terms of Use. 
<br><br>
The Terms of Use are established to protect the interest of the member service providers and all our users and constitute a contract between the users and member service providers. By completing the registration procedures, or beginning to use the member services available from ZyXEL, you are deemed to have understood and completely agreed to all the terms and conditions under the Terms of Use.
<br><br>
■ All members have the obligation to properly keep their password.<br>
1.  All members are required to properly keep their password without disclosing it to others or allow others to use it. All acts performed under the same member account and password will be deemed as the personal acts of the member him/herself and the password keeper.
2.  All members are required to provide their correct personal information during registration. When any false information is found, ZyXEL will have the discretion to suspend or terminate the membership. In case of violation of the law of the Republic of China or the place where a member is located, actions will be taken according to the law.
3.  If a member discovers or suspects a third person is using his/her member account or password without authorization, he/she should immediately notify ZyXEL so that necessary precautionary measures can be taken.
<br><br>
■ Protection of members' privacy.<br>
1.  In any of the following circumstances, ZyXEL may access or provide the member's personal or relevant telecommunication information to the competent authorities, or a third person who claims his/her rights have been infringed with proper supporting documents:
a.  According to law;
b.  As required by judicial authority or other competent authorities under statutory procedure;
c.  To ensure personal safety of other members or third parties in case of emergency; or
d.  Necessary information about cash flows and logistics services generated by members in their activities through ZyXEL.
<br>
2.  Without a member's prior consent, ZyXEL will not disclose to others the name, address, email or other legally protected personal information of a member contained in the personal information provided by the member to us.
<br>
3.  For purposes of marketing, market analysis, statistics or research, or to provide members with customized services or value-added services, members agree ZyXEL or its strategic partners may record, keep and use the information or records stored at or generated by members' use of this website, and may disclose or use statistical data without disclosing specific information.
<br>
4.  Members agree ZyXEL may send them information about various types of activities and other contents at any time.
<br><br>
■ Restrictions on Use.<br>
1.  For legal purpose only. Members may use the services available from ZyXEL and member devices for legal, legitimate and proper purpose only. No member should use the services available from ZyXEL and member devices in any manner that is  illegal, illegitimate or improper.
2.  Monitoring. ZyXEL may monitor the use of services available from ZyXEL to make sure there is no activity in breach of this agreement. If ZyXEL suspects any activity is in breach of this agreement, or if ZyXEL believes it is necessary to protect the services available from ZyXEL or its parent company, affiliates, directors, officers, distributors and employees from any harm, we may interrupt or intercept all communications.
3.  Provide information to the government and third parties.
If ZyXEL determines a member is using the services from ZyXEL and member devices for illegal purpose, ZyXEL will forward the relevant communication records and other information (including member's identification) to appropriate prosecutors' offices/investigation authorities for further investigations. Members agree ZyXEL may forward any of these communication records and information to the above authorities. Also, ZyXEL may, upon the following requests, disclose member's name, telephone number, credit card information and other personal information, communications and correspondences sent and/or received by any member, and any other information about member account held by ZyXEL, including but not limited to service types, service years, MAC address, IP address, email address and all other account information:
a.  To respond to requests from law enforcement or other governmental agencies;
b.  As ordered by law, regulations, statutes, writ of summons, search warrant, or court order;
c.  As required for identification or communication, or legal action against a person who may have abused the services and/or devices;
d.  To protect the rights and interests and assets of ZyXEL; or
e.  In case of emergency where it is necessary to disclose this information to protect the clients of ZyXEL or third persons from imminent damage.
<br><br>
■ Disclaimer.<br>
Information on the ZyXEL website and services and products of ZyXEL are all provided "as is". In no circumstance shall ZyXEL provide any other guarantee, explicitly or implicitly, including but not limited to implied guarantee on merchantability, fitness of service or product for particular purpose, ownership or non-infringement on another's rights or interests, or any guarantee arising from transactions, business dealings or contract performance. In addition, we do not guarantee there will be no breakdowns, delays, interruptions, errors, poor voice quality for the ZyXEL website, services or products, or there will be no loss to contents, data or information.
Members hereby acknowledge certain products and services available from ZyXEL are not encrypted and this type of information may be intercepted in the transmissions involving ZyXEL, our services or products, and ZyXEL does not guarantee this software, the ZyXEL website, services or products are absolutely secure. Members hereby agree to bear any and all risks associated with unauthorized access to member information during transmission of this type of information.
In no circumstances shall ZyXEL or its officers, directors, employees, affiliates, suppliers or distributors, or any other service providers or vendors who provide services, devices or products relating to our services to clients be liable for any compensations for damages from unauthorized use of the transmission facilities or peripherals of ZyXEL or members, or unauthorized access to member's data files, programs, procedures or information for purpose of alteration, stealth or sabotage by way of accident, fraud, deceived device or any other method, whether or not such damages are due to negligence of ZyXEL or its service providers or vendors.
The statements and descriptions about our services or devices made by ZyXEL or the distributors or suppliers of ZyXEL are only of notices and shall not be of any form of guarantee. As the information available on this website covers various jurisdictions around the world, not all the products, prices or programs mentioned herein are available or offered in the country/territory where the member is located. Please contact your local sales representative for more details about the products and services available in your country/territory.
While ZyXEL makes all possible efforts to provide accurate information on the ZyXEL website, ZyXEL shall not be liable for accuracy of the information contained therein. ZyXEL may change the programs or products mentioned in this agreement at any time without notice. The products or service not available from ZyXEL as mentioned in this agreement are for reference only and we do not endorse or suggest use of these products or services.
<br><br>
■ Limitation on Liability.<br>
In no circumstances shall ZyXEL, its officers, directors, affiliates, employees, licensors or Internet service providers be liable for any damages including direct, indirect, incidental, consequential or punitive damages, litigation or costs, including but not limited to losses of goodwill, profits or data or interruption of operation, arising from or in connection with this agreement and/or transactions contemplated under this agreement, including use or inability to use the ZyXEL website, services and/or products, inability to use emergency numbers to reach emergency repair staff or get urgent assistance, and unauthorized access or change to member's communication records or information, even if ZyXEL has been aware of the possibility of the above damages. In view of the evolving development of new technologies enabling hacking, Internet attacks, and interception of incoming and outgoing information, ZyXEL does not guarantee that use of products, software or services or any equipment, system or Internet utilizing its products, software or services do not have any loopholes that may be taken advantage for hacking, attacks or information interception.
As some jurisdictions do not permit exclusions or limitations on the liabilities for implied guarantee or consequential or incidental damages, these restrictions in this clause may not apply to certain members. Members may have other legal rights depending on the jurisdictions they are located. These limitations shall apply to the greatest extent as permitted under the law.
<br><br>
■ Intellectual Property Rights.<br>
All works and information, their copyrights, patents, trademarks, trade secrets and other intellectual property rights, ownership and other rights on the ZyXEL website are the properties owned by ZyXEL or their original authors. Unless prior authorization from ZyXEL or the right holders is obtained, no members shall reproduce, transmit, adapt, edit or use any of the above in any way or for any purposes. Otherwise, he/she will be held liable under the law.
<br><br>
■ Waiver of Claims or Causes of Action.<br>
Members waive any and all claims or causes of action arising from and/or in connection with our services, except for those claims or causes of action arising from our gross negligence, omission, or intentional mistake.
<br><br>
■ Agreement Amendment.<br>
We may amend the terms and conditions of this agreement by publishing the amendments on the ZyXEL website at any time. A member's continued use of the ZyXEL website, our services and/or products constitutes his/her acceptance of these amendments. This agreement may not be modified in any manner unless amendments are made by a written agreement signed by the member with us.
<br><br>
■ Severability.<br>
Invalidity of part or all of any provisions under this agreement shall not affect the validity of any other provisions.
<br><br>
■ Governing law and Court of Jurisdiction.<br>
The rights and obligations between members and the ZyXEL shall be governed by the Internet policies and the law of the Republic of China. The Taipei District Court of Taiwan has the jurisdiction for the first instance over any disputes arising therefrom. .
For matters not provided for in any statements or provisions made by ZyXEL, we will do everything we can to resolve the issues with disputed parties on a bona fide, equal and mutual basis.
<br><br>
■ Termination of Membership.<br>
ZyXEL reserves the rights to change the contents of our services or terminate our services available to any member account, of which relevant members will be notified with an email from us.
<br><br>
■ Internet Disasters.<br>
As signing up our services is free of charge, members understand and agree that operation of the ZyXEL system may experience interruptions, malfunctions, delays, errors in data transmission or storage due to force majeure events such as breakdowns or failures of the software and hardware equipment of the Internet systems of relevant telecommunication service providers or natural disasters, for which ZyXEL shall not be liable for any damages, compensations or reimbursements therefrom.

app/views/hint/agreement.html.erb
<% provide(:flow, I18n.t("titles.terms")) %>
<div class="zyxel_content">

  <div class="agree_note_box">
    <% if I18n.locale.to_s  == "zh-TW" %>
      <%= render "hint/terms/zh_TW" %>
    <% else %>
      <%= render "hint/terms/en" %>
    <% end %>
  </div>

    <div class="zyxel_btn_area">
      <a class="zyxel_btn_ok" href="#" onclick="window.close();"><%= I18n.t("labels.confirm") %></a>
    </div>
</div>

app/views/hint/confirm.html.haml
- content_for :title, I18n.t('titles.sign_up')

- content_for :precontent do
  .process_indicator_wrapper
    %svg.process_indicator
      %circle.circle1.apply_theme
      %line.apply_theme{:x1 => 23, :y1 => 15, :x2 => 38, :y2 => 15}
      %circle.circle2.apply_theme
      %line.apply_theme{:x1 => 62, :y1 => 15, :x2 => 77, :y2 => 15}
      %circle.circle3.apply_theme

.content_wrapper.normal
  .inner_title
    %h4
      = I18n.t("warnings.applied_success")
    %p
      = session[:notice]
  .spacer{ :style => "height: 220px;" }

  = link_to I18n.t("labels.resend_confirmation"), new_confirmation_path(:user), class: 'btn btn-custom btn-block'
  = link_to I18n.t("labels.confirm"), root_path, class: 'btn btn-custom btn-block'

app/views/hint/confirm_sent.html.haml
- content_for :title, I18n.t('titles.sign_up')

- content_for :precontent do
  .process_indicator_wrapper
    %svg.process_indicator
      %circle.circle1.apply_theme
      %line.apply_theme{:x1 => 23, :y1 => 15, :x2 => 38, :y2 => 15}
      %circle.circle2.apply_theme
      %line.apply_gray{:x1 => 62, :y1 => 15, :x2 => 77, :y2 => 15}
      %circle.circle3.apply_gray

.content_wrapper.normal
  .inner_title
    %h4
      / = fa_icon('check-circle-o')
      = I18n.t("devise.confirmations.resend")
    %p
      = I18n.t("devise.confirmations.confirm_sent")
  .spacer{ :style => "height: 220px;" }

  = link_to I18n.t("labels.ok"), destroy_user_session_path, class: 'btn btn-custom btn-block'

app/views/hint/reset.html.haml
- content_for :title, I18n.t("titles.forgot_password")

/ - content_for :precontent do
/   .process_indicator_wrapper
/     %svg.process_indicator
/       %circle.circle1.apply_theme
/       %line.apply_theme{:x1 => 23, :y1 => 15, :x2 => 38, :y2 => 15}
/       %circle.circle2.apply_theme
/       %line.apply_theme{:x1 => 62, :y1 => 15, :x2 => 77, :y2 => 15}
/       %circle.circle3.apply_theme

.content_wrapper.normal
  .inner_title
    %h4
      = I18n.t("warnings.forgot_password")
    %p
      = session[:notice]
  .spacer{ :style => "height: 220px;" }

  = link_to I18n.t("labels.confirm"), root_path, class: 'btn btn-custom btn-block'

app/views/hint/sent.html.haml
- content_for :title, I18n.t("titles.forgot_password")

.content_wrapper.normal
  .inner_title
    %h4
      = fa_icon('check-circle-o')
      = I18n.t("warnings.sent_email")
    / %br
    %p
      = I18n.t("devise.passwords.send_instructions")
  .spacer{ :style => "height: 220px;" }

  / = link_to I18n.t("labels.submit"), "/", class: 'btn btn-custom btn-block'
  = link_to I18n.t("labels.confirm"), root_path, class: 'btn btn-custom btn-block'
  .btn-cancel
    = link_to I18n.t("labels.resend_confirmation"), new_user_password_path

app/views/hint/signup.html.haml
- content_for :title, I18n.t('titles.sign_up')

- content_for :precontent do
  .process_indicator_wrapper
    %svg.process_indicator
      %circle.circle1.apply_theme
      %line.apply_theme{:x1 => 23, :y1 => 15, :x2 => 38, :y2 => 15}
      %circle.circle2.apply_theme
      %line.apply_theme{:x1 => 62, :y1 => 15, :x2 => 77, :y2 => 15}
      %circle.circle3.apply_theme

.content_wrapper.normal
  .inner_title
    %h4
      = I18n.t("devise.confirmations.confirmed")
    %p
      = I18n.t("warnings.confirmation_success")
  .spacer{ :style => "height: 220px;" }

  = link_to I18n.t("labels.confirm"), root_path, class: 'btn btn-custom btn-block'