config/routes.rb
Rails.application.routes.draw do

  # Routes for Pcloud portal
  constraints :host => Settings.environments.portal_domain do
    devise_scope :user do
      # setting root path to welcome index page, if user signed in
      authenticated :user do
        root 'welcome#index', as: :authenticated_root
      end

      # setting root path to sign in page, if user not sign in
      unauthenticated do
        root 'sessions#new', as: :unauthenticated_root
      end
    end

    use_doorkeeper scope: 'oauth' do
      controllers authorizations: 'oauth2/authorizations',
                  tokens: 'oauth2/tokens',
                  applications: 'oauth2/applications',
                  authorized_applications: 'oauth2/authorized_applications'
    end
    get 'oauth/logout', to: 'oauth2/authorizations#logout'

    get 'hint/signup'
    get 'hint/confirm'
    get 'hint/reset'
    get 'hint/sent'
    get 'hint/agreement'
    get 'hint/confirm_sent'
    get 'help', to: 'help#index'

    devise_for :users, :controllers => {
      :registrations => "registrations",
      :confirmations => 'confirmations',
      :sessions => "sessions",
      :passwords => 'passwords',
      :omniauth_callbacks => "users/omniauth_callbacks"}

    devise_scope :user do
      get   'users/confirmation/edit', to: 'confirmations#edit'
      patch 'users/confirmation',      to: 'confirmations#update'
      get   'oauth/new',               to: 'users/omniauth_callbacks#new'
      post  'oauth/new',               to: 'users/omniauth_callbacks#confirm'
      get   'oauth/login',             to: 'users/omniauth_callbacks#login'
      post  'oauth/login',             to: 'users/omniauth_callbacks#logining'
    end

    get 'personal/profile'

    scope module: 'oauth2' do
      namespace :api do
        namespace :v1 do
          get 'my/info', to: 'my#info', format: 'json'
        end
      end
    end

    scope :path => '/d/oauth', :module => "api/devices" do
      post 'authorize', to: 'authorize#create', format: 'json'
    end

    scope :path => '/healthy/1/', :module => "api/healthy" do
      get 'status', to: 'status#show', format: 'json'
    end
  end

  # Catch all routes
  root "application#raise_not_found!", via: :all
  get "*path", to: "application#raise_not_found!", via: :all
end

app/controllers/oauth2/authorized_applications_controller.rb
class Oauth2::AuthorizedApplicationsController < Doorkeeper::AuthorizedApplicationsController
  include ExceptionHandler
  include CheckUserConfirmation
  include Locale
  include Theme

  layout 'application'

  before_action :authenticate_resource_owner!

end

app/views/doorkeeper/authorized_applications/_delete_form.html.erb
<%- submit_btn_css ||= 'btn btn-link' %>
<%= form_tag oauth_authorized_application_path(application) do %>
  <input type="hidden" name="_method" value="delete">
  <%#= submit_tag t('doorkeeper.authorized_applications.buttons.revoke'), onclick: "return confirm('#{ t('doorkeeper.authorized_applications.confirmations.revoke') }')", class: submit_btn_css %>
  <%= submit_tag t('doorkeeper.authorized_applications.buttons.revoke'), onclick: "return confirm('#{ t('doorkeeper.authorized_applications.confirmations.revoke') }')", class: 'btn btn-danger btn-xs' %>
<% end %>

app/views/doorkeeper/authorized_applications/index.html.erb
<% provide(:disable_alert, "hidden") %>
<div class="zyxel_bread">
  <span><%= t('doorkeeper.authorized_applications.index.title') %></span>
  <%= link_to I18n.t("labels.back_to_home"), authenticated_root_path, class: "zyxel_btn_main icon_home" %>
</div>
<div class="personal">
  <div class="zyxel_content" style="max-width: 600px;">
    <% if flash[:notice] %>
      <div class="zyxel_arlert_area">
        <span class="error_message"><%= flash[:notice] %></span>
      </div>
    <% end %>
    <table class="zyxel_table_style zyxel_table_style1 user_info" style="word-break: break-all;">
    <!-- <table class="zyxel_table_style1"> -->
      <thead>
      <tr>
        <th class="col-xs-8 col-sm-4 col-md-4 col-lg-4"><%= t('doorkeeper.authorized_applications.index.application') %></th>
        <th class="col-xs-3 col-sm-4 col-md-4 col-lg-4"><%= t('doorkeeper.authorized_applications.index.created_at') %></th>
        <th class="col-xs-1 col-sm-4 col-md-4 col-lg-4"></th>
      </tr>
      </thead>
      <tbody>
      <% @applications.each do |application| %>
        <tr>
          <td><%= application.name %></td>
          <td><%= application.created_at.strftime(t('doorkeeper.authorized_applications.index.date_format')) %></td>
          <td><%= render 'delete_form', application: application %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

     <div class="zyxel_btn_area i18n_fix">
      <%= link_to I18n.t("labels.back_to_profile"), personal_profile_path, class: "zyxel_btn_ok" %>
    </div><!-- zyxel_btn_area -->

  </div> <!-- content -->
</div> <!-- personal -->

<!-- <header class="page-header">
  <h1><%#= t('doorkeeper.authorized_applications.index.title') %></h1>
</header>
<main role="main">
  <table class="table table-striped">
    <thead>
    <tr>
      <th><%#= t('doorkeeper.authorized_applications.index.application') %></th>
      <th><%#= t('doorkeeper.authorized_applications.index.created_at') %></th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <%# @applications.each do |application| %>
      <tr>
        <td><%#= application.name %></td>
        <td><%#= application.created_at.strftime(t('doorkeeper.authorized_applications.index.date_format')) %></td>
        <td><%#= render 'delete_form', application: application %></td>
      </tr>
    <%# end %>
    </tbody>
  </table>
</main> -->

app/views/doorkeeper/authorized_applications/index.html.haml
- content_for :title, I18n.t('doorkeeper.authorized_applications.index.title')

.content_wrapper.normal
  .inner_title
    %h4
      = fa_icon('list')
      = I18n.t('doorkeeper.authorized_applications.index.title')
    %p
      -if flash[:notice]
        %span= flash[:notice]

  - if @applications.empty?
    %p= I18n.t('doorkeeper.authorized_applications.index.no_application')
  - else
    %table.authorized_app_table
      %tr
        %th= I18n.t('doorkeeper.authorized_applications.index.application')
        %th= I18n.t('doorkeeper.authorized_applications.index.last_updated_at')
        %th
      - @applications.each do |application|
        %tr
          %td= application.name
          %td= application.access_tokens.last.created_at.strftime(t('doorkeeper.authorized_applications.index.date_format'))
          %td= render 'delete_form', application: application

  = link_to I18n.t("labels.back_to_profile"), personal_profile_path, class: "btn btn-custom btn-block"

app/views/doorkeeper/authorized_applications/index_backup.html.erb
<% provide(:disable_alert, "hidden") %>
<div class="zyxel_bread">
  <span><%= t('doorkeeper.authorized_applications.index.title') %></span>
  <%= link_to I18n.t("labels.back_to_home"), authenticated_root_path, class: "zyxel_btn_main icon_home" %>
</div>
<div class="personal">
  <div class="zyxel_content" style="max-width: 600px;">
    <% if flash[:notice] %>
      <div class="zyxel_arlert_area">
        <span class="error_message"><%= flash[:notice] %></span>
      </div>
    <% end %>
    <table class="zyxel_table_style zyxel_table_style1 user_info" style="word-break: break-all;">
    <!-- <table class="zyxel_table_style1"> -->
      <thead>
      <tr>
        <th class="col-xs-8 col-sm-4 col-md-4 col-lg-4"><%= t('doorkeeper.authorized_applications.index.application') %></th>
        <th class="col-xs-3 col-sm-4 col-md-4 col-lg-4"><%= t('doorkeeper.authorized_applications.index.created_at') %></th>
        <th class="col-xs-1 col-sm-4 col-md-4 col-lg-4"></th>
      </tr>
      </thead>
      <tbody>
      <% @applications.each do |application| %>
        <tr>
          <td><%= application.name %></td>
          <td><%= application.created_at.strftime(t('doorkeeper.authorized_applications.index.date_format')) %></td>
          <td><%= render 'delete_form', application: application %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

     <div class="zyxel_btn_area i18n_fix">
      <%= link_to I18n.t("labels.back_to_profile"), personal_profile_path, class: "zyxel_btn_ok" %>
    </div><!-- zyxel_btn_area -->

  </div> <!-- content -->
</div> <!-- personal -->

<!-- <header class="page-header">
  <h1><%#= t('doorkeeper.authorized_applications.index.title') %></h1>
</header>
<main role="main">
  <table class="table table-striped">
    <thead>
    <tr>
      <th><%#= t('doorkeeper.authorized_applications.index.application') %></th>
      <th><%#= t('doorkeeper.authorized_applications.index.created_at') %></th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <%# @applications.each do |application| %>
      <tr>
        <td><%#= application.name %></td>
        <td><%#= application.created_at.strftime(t('doorkeeper.authorized_applications.index.date_format')) %></td>
        <td><%#= render 'delete_form', application: application %></td>
      </tr>
    <%# end %>
    </tbody>
  </table>
</main> -->